### ISSUE TITLE
Client throws an error if you try to send empty list of DataPoints

### ISSUE THREAD

**Issue by rshivane** [ApptuitAI/apptuit-py#23]
Calling `Apptuit.send` with an empty list of `DataPoints` results in the following error.

**Expected**:  It should do nothing silently

```
Error sending data points to Apptuit
Traceback (most recent call last):
  File "/home/ubuntu/scraper.py", line 56, in fetch_metrics
    client.send(data_points)
  File "/usr/local/lib/python2.7/dist-packages/apptuit/apptuit_client.py", line 112, in send
    "%d and response: %s" % (response.status_code, response.content))
ApptuitException: PUT request failed with response code: 400 and response: {"error":{"code":400,"message":"No datapoints found in content","request":"4440b89e-31f0-4aef-90c0-42b2a5cb6f1d"}}
```

**Comment by JoeHitHard** [comment]
resolved
```
    def send(self, datapoints):
        if not datapoints:
            return
```
